General:
  updateInterval: 2 #Update servers from CloudNet (In sec)
  captchaType: 3 #type captcha 1, 2, 3 or 0 - disable
  nextConnect: Hub #Name server to connect when success login
  timeSessions: 1800 #Autologin when reconnect (In sec)
  timeLogin: 30 #If user not login in this time - kick him (In sec)
  timeReg: 30 #If user not registration in this time - kick him (In sec)
  timeCaptcha: 30 #If user not success captcha in this time - kick him (In sec)

Database:
  host: 152.70.52.190
  port: 3306
  database: TCBack
  ssl: false
  user: root
  password: oz7WXg3hpw6JxGmwVOo9F!ObGBf4tNf7c47gDgbQPvmY6%iA5w
  hikari:
    minConnections: 10
    maxConnections: 100
    timeout: 30 #In sec

SMTP:
  enable: false
  host: smtp.gmail.com
  port: 465
  user: userSmtp
  password: passwordSmtp

Username:
  excludeSymbol:
    - '$'
    - ' '
    - "-"

Password:
  minLength: 6
  maxLength: 16
  banned:
    - '123456'
    - '654321'
