name: TAS
version: ${project.version}
main: me.towecraft.TAS
api-version: 1.13
author: Armatura
description: Auth System

commands:
  connect:
    description: 'Connect to current server'
  l:
    description: 'Login command'
  login:
    description: 'Login command'

  r:
    description: 'Registration command'
  reg:
    description: 'Registration command'

  rec:
    description: 'Recovery password command'
  recovery:
    description: 'Recovery password command'
