name: TAS
version: 1.0-Alpha
main: me.towecraft.TAS
api-version: 1.13
author: Armatura
description: Auth System Module

commands:
  connect:
    description: 'Connect to current server'
  l:
  log:
  login:

  r:
  reg:
  register:
